[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


[rpc_endpoints]
bsc-mainnet = "https://bsc-dataseed.binance.org/"
bsc-testnet = "https://data-seed-prebsc-1-s1.binance.org:8545"
bsc_testnet = "${BSC_TESTNET_RPC_URL}"

# You can set a default for the script:
default_rpc_url = "bsc-testnet"

[etherscan]
bsc_testnet = { key = "${BSCSCAN_API_KEY}" }